# -*- coding: utf-8 -*-
"""imageAugmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HL60b_TQF4JGcbWxnRI55m1INvZqw6VI
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
import numpy as np
import argparse
from imutils import paths
import cv2

from google.colab import drive
drive.mount('/content/drive/')

datapath="/content/drive/My Drive/"
out="/content/drive/My Drive/test_"

print("[INFO] loading images...")
imagePaths = list(paths.list_images(datapath))
print(imagePaths)
data=[]

for imagePath in imagePaths:
    print(imagePath)
    image = cv2.imread(imagePath)
	  #cv2.imshow(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    print(image)
    print("////////////////////////")
    image = img_to_array(image)
    print(image)
    image = np.expand_dims(image, axis=0)
    data.append(image)
datanp=np.array(data)

print(len(datanp))
aug = ImageDataGenerator(
	rotation_range=30,
	zoom_range=0.15,
	width_shift_range=0.2,
	height_shift_range=0.2,
	shear_range=0.15,
	horizontal_flip=True,
	fill_mode="nearest")
total = 0
imageGen=[]

print("[INFO] generating images...")

# augmentedImages=[]
for i in range(len(datanp)):
        print("Generating is running")
  
        imageGen= aug.flow(datanp[i], batch_size=1, save_to_dir=out,
        save_prefix="image", save_format="jpg")
        for image in imageGen:
	# increment our counter
	        total += 1
	# if we have reached the specified number of examples, break
	# from the loop
	        if (total%6==0):
				#total = 0
		        break

