# -*- coding: utf-8 -*-
"""SVM+Hog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1il8-IVFhUQ67MuPwX2glJRiz8y8Tm0LH
"""

import os
import numpy as np
import cv2
import pickle
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from skimage.io import imread
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure
import matplotlib.pyplot as plt
from argparse import ArgumentParser
import argparse
from sklearn.svm import LinearSVC
from skimage import feature

from google.colab import drive
drive.mount('/content/drive/')

dir = '/content/drive/My Drive/augmented'
categories = ['test_Yuya','test_Userkaf','test_Champollion','test_Snotm','test_Hetep']
images = []
data = []

for category in categories:
    path = os.path.join(dir,category)
    label = categories.index(category)
    
    for img in os.listdir(path):
        imgpath = os.path.join(path,img)
        datimage = cv2.imread(imgpath,0)
        datimage = cv2.resize(datimage,(128, 256))
        image = np.array(datimage).flatten()
        hog_desc = feature.hog(datimage, orientations=9, pixels_per_cell=(8, 8),cells_per_block=(2, 2), transform_sqrt=True, block_norm='L2-Hys')
        
        data.append([hog_desc,label])
        
pick_in = open('/content/drive/My Drive/feature_extraction.pickle','wb')
pickle.dump(data,pick_in)
pick_in.close()

pick_in = open('/content/drive/My Drive/feature_extraction.pickle','rb')
data = pickle.load(pick_in)
pick_in.close()

random.shuffle(data)
features = []
labels = []

for feature, label in data:
    features.append(feature)
    labels.append(label)

xtrain,xtest,ytrain,ytest=train_test_split(features,labels,test_size=0.30)
model = SVC(C=20,kernel='linear', gamma='auto',)
model.fit(xtrain,ytrain)

svm_model=open('/content/drive/My Drive/svm_model.sav','wb')
pickle.dump(model,svm_model)
svm_model.close()

svm_read=open('/content/drive/My Drive/svm_model.sav','rb')
model=pickle.load(svm_read)
svm_read.close()

prediction=model.predict(xtest)
accuracy = model.score(xtest,ytest)

categories = ['test_Yuya','test_Userkaf','test_Champollion','test_Snotm','test_Hetep']
print('Accuracy: ',accuracy)
print('Prediction is: ',categories[prediction[0]])

from sklearn import svm
from sklearn.metrics import classification_report
clf = svm.SVC(kernel='linear')
clf.fit(xtrain, ytrain)
y_pred = clf.predict(xtest)
print("Accuracy:",metrics.accuracy_score(ytest, y_pred))
print("Precision:",metrics.precision_score(ytest, y_pred, pos_label='positive',average= 'weighted'))
print("Recall:",metrics.recall_score(ytest, y_pred,pos_label='positive',average= 'weighted'))